version: '3.7'
services:
  nginx:
    image: nginx:1.17.2-alpine
    ports:
      - '8080:80'
    volumes:
      - ./web:/var/www/html
      - ./build/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - redis
  php:
    build: ./build/php
    user: '1000:1000'
    volumes:
      - ./web:/var/www/html
      - ./build/php/php.ini-development:/usr/local/etc/php/php.ini-development
  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379